# Logo
logo: /content/logo_round.png # Empty this to unset logo and show site title in the same place

# Header
menu:
  Home: .
  "Boostrapping MVC": about/bootstrapping-mvc.html 
  Archives: archives
  Testimonials: about
  GenFu: about/genfu.html

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # Whether to show profile bar
gravatar: false # Whether to use gravatar with the email. If you do, put your email address in your site's `_config.yml`.

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- coffee
- tagcloud
- archive
thumbnail: false

# Contacts
contacts:
  twitter: 'CanadianJames'
  github: http://github.com/MisterJames
  rss: atom.xml
  linkedin: https://ca.linkedin.com/in/canadianjames
  youtube: https://www.youtube.com/user/CodingMisterJames/
  
# Links
links:
  Hexo: http://hexo.io

# CDN
cdn: # You can choose "useso" instead of "google apis"(default).
# cdn: useso
# OR
# cdn:

# Miscellaneous
google_site_verification:
google_analytics: UA-2868185-6
favicon: content/avatar.png
twitter: CanadianJames
google_plus:
fb_admins:
fb_app_id:
